export const TELEMETRY_SCHEMA_VERSION = 1;
export const MAX_BATCH_EVENTS = 100;
export const MAX_REQUEST_BYTES = 256 * 1024;
export const MAX_EVENT_STRING_BYTES = 2 * 1024;
export const DEFAULT_RETENTION_DAYS = 90;
export const DEFAULT_RATE_LIMIT_WINDOW_MS = 60_000;
export const DEFAULT_RATE_LIMIT_MAX_REQUESTS = 120;
export const DEFAULT_RATE_LIMIT_MAX_KEYS = 10_000;
